### ISSUE TITLE
microlens-th is not deterministic

### ISSUE THREAD

**Issue by niteria** [aelve/microlens#83]
Note: I'm doing creating this issue to raise awareness and to determine if this is something that could be fixed on microlens-th side.

Background: For various [reasons](https://ghc.haskell.org/trac/ghc/wiki/DeterministicBuilds#Motivation) it's desirable to have GHC produce ABI-compatible binaries given the same input, flags and the environment.
Now, TemplateHaskell gives no guarantees about this, you could generate different code depending on the phase of the moon.
As it turns out `microlens-th` is unintentionally nondeterministic. There's no code that accesses the environment nor does some suspect thing and yet, it will not always produce the same code in the same conditions.

The core of the issue is that GHC exposes a bit more about the internals than it should. Its `Name` type holds a `Unique`. For various [reasons](https://ghc.haskell.org/trac/ghc/wiki/DeterministicBuilds#NondeterministicUniques) `Uniques` are not stable across recompilations. As it happens the `Ord` instance for `Name` is based on `Unique` meaning that the relative order `Names` might change between compilations.

As it happens `microlens-th` holds a `Set/Map` of these names that later determines the order of type variables in the generated definition.

There are multiple valid stances to take here:

1. TH is nondeterministic anyway, so why bother fixing this
2. This is bad and should be [fixed](https://phabricator.haskell.org/D2288) on GHC side
3. This is bad, but GHC shouldn't bother fixing it, it's up to the library to ensure the determinism

Now I'm leaning towards 2., but the problem with that approach is that the soonest this can get fixed is for GHC 8.2, which is probably a year away.

Related discussions:
https://mail.haskell.org/pipermail/ghc-devs/2016-May/012163.html
https://mail.haskell.org/pipermail/ghc-devs/2016-June/012181.html

**Comment by neongreen** [comment]
microlens-th uses code from lens, and so this issue [applies to lens](https://github.com/ekmett/lens/blob/bdb7e9142e83ff92a3f914a7ffc7ea4f5582a6d9/src/Control/Lens/Internal/FieldTH.hs#L601) too. I can fix it by pairing the set with a list or by implementing an ordered set in [some other way](http://stackoverflow.com/a/25336511/615030), but then when lens fixes the issue as well I'd have to scrap my solution and copy theirs (because I want to keep my code in sync with lens's code for easier merging).

@glguy (the author of the original TH code) is already aware of the issue, but I suggest you file an issue at lens's bug tracker anyway so that it wouldn't be forgotten accidentally.

**Comment by glguy** [comment]
https://github.com/glguy/irc-core/commit/4a498dd21a5f635273150bed0a9f22807b7547fd
