### ISSUE TITLE
Why no abbreviatedFields in microlens-th?

### ISSUE THREAD

**Issue by qrilka** [aelve/microlens#84]
I was trying to checkout our project migrated to microlens but stuck at the moment with `abbreviatedFields` - probably I could port it from `lens` but why doesn't it exist already?

**Comment by neongreen** [comment]
microlens is developed on the “add things that most people need and then add things that users explicitly request” basis. Now that you have requested `abbreviatedFields`, I'll add it :)

**Comment by qrilka** [comment]
I've tried to add it outside of `microlens` but it appears that `LensRules` are not quite extensible in that direction :(
So I can't define `abbreviatedFields` having no access to `_fieldToDef` field. Not sure if it could be useful for other cases though.

**Comment by qrilka** [comment]
Actually the main motivation for my attempt is https://github.com/ghcjs/ghcjs/issues/449 - do you know if there were other (successful?) attempts to use `microlens` with GHCJS?

**Comment by neongreen** [comment]
microlens can be compiled with GHCJS (as I checked yesterday), but that's all I know. If your main problem is that any use of TH slows down your builds drastically, using microlens instead of lens won't help you. You might have better luck with generating lenses using lens-family-th (you can keep using microlens for the rest) since lens-family-th's code seems to be simpler. You might also try using a preprocessor instead of Template Haskell.

`LensRules` are meant to be configured with lenses in the “Configuring lens rules” section. The `_fieldToDef` field in particular can be set with the `lensField` lens.

**Comment by qrilka** [comment]
yes, such thoughts also came to me so maybe it's time to dig into GHCJS internals but I'm not yet sure if I'm brave enough :)

**Comment by neongreen** [comment]
Fixed in microlens-th-0.4.1.
